### ISSUE TITLE
python 3 compatibility for print statements in fabfile.py

### ISSUE THREAD

**Issue by prheenan** [JossinetLab/RNA-Science-Toolbox#2]
Hello, 

I am using python 3.7.10:

    python --version
    Python 3.7.10

When I attempt to run "fab python" in the top level directory, I get the following error:

    Traceback (most recent call last):
    File "/Users/patrickheenan/opt/anaconda3/envs/assemble2/lib/python3.7/site-packages/fabric/main.py", line 673, in main
        docstring, callables, default = load_fabfile(fabfile)
    File "/Users/patrickheenan/opt/anaconda3/envs/assemble2/lib/python3.7/site-packages/fabric/main.py", line 174, in load_fabfile
        imported = importer(os.path.splitext(fabfile)[0])
    File "/Users/patrickheenan/scratch/RNA-Science-Toolbox/fabfile.py", line 40
        print "You need to install the following Python packages:"

    SyntaxError: Missing parentheses in call to 'print'. 
    Did you mean print("You need to install the following Python packages:")?

Per the error messages, the problem appears to be a few missing parenthesis. I've attached a "fabfile.py.zip" which runs properly, as well as a screenshot of the diff. If you include these changes, running "fab python" will work for python 3.7.10.

<img width="572" alt="Screen Shot 2021-03-06 at 9 54 52 AM" src="https://user-images.githubusercontent.com/9592535/110210909-00306b00-7e62-11eb-917f-83a4967a5d94.png">

[fabfile.py.zip](https://github.com/fjossinet/RNA-Science-Toolbox/files/6095540/fabfile.py.zip)

**Comment by fjossinet** [comment]
Hi,

thank you for this fix. I will commit it.

Best
